# Generated by Django 2.1 on 2018-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=140)),
                ('tweet_date', models.DateTimeField(verbose_name='tweet date')),
            ],
        ),
    ]
